### ISSUE TITLE
微信小程序远程调试可以,iOS13.3.7部署到真机则报错,请指教

### ISSUE THREAD

**Issue by sanruby** [planet0104/miniprogram-rust-wasm#2]
微信小程序远程调试可以,iOS13.3.7部署到真机则报
Error loading Rust wasm module 'demo': <ReferenceError: Can't find variable: WebAssembly>
2 (in promise) MiniProgramError
Can't find variable: WebAssembly
at WebAssembly (demo.js:75:28)
at (WASubContext.js:2:66139)
at (WASubContext.js:2:66247)
at e (WASubContext.js:2:68700)
at (WASubContext.js:2:32938)
at r (WASubContext.js:2:32637)
at h (WASubContext.js:2:111445)
at (WASubContext.js:2:112266)
at (WASubContext.js:2:94559)
at (WASubContext.js:2:101100)
_onNativeTimer
global code

**Comment by shixm1102** [comment]
请问这个问题解决了吗？我也遇到了同样的问题
